// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Strip whitespace/newlines that Render env vars can introduce — newlines in
// HTTP headers cause Chrome to throw "Failed to execute 'fetch': Invalid value".
const clean = (v: string | undefined) => (v || "").replace(/\s+/g, "");

const SUPABASE_URL =
  clean(import.meta.env.VITE_SUPABASE_URL) ||
  "https://kroqooyprcvzzgkclvmy.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  clean(import.meta.env.VITE_SUPABASE_ANON_KEY) ||
  clean(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtyb3Fvb3lwcmN2enpna2Nsdm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NTQ5ODEsImV4cCI6MjA4OTUzMDk4MX0.yqmJ_7Ka2qgITspGqhFCpET4fM7-LEvtfrTQo8EsHEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});